Update composer.json for SF7
ecphp/cas-bundle pull request #98
Opened 2024-02-20 07:55 UTC by StudioAH

dependencies updates for symfony 7

This PR

- [x]
- [ ]
- [ ]

Follows #. Related to #. Fixes #.

2024-02-20 08:01 UTC, drupol reviewed
Thanks for the contribution!

Do you think making it compatible with Symfony 6 _and_ 7 would be a good idea ?

2024-02-20 09:35 UTC, drupol commented
Hello,

Why did you close the PR ?

FYI, I received a request for making it compatible with SF7 yesterday, I gave more information in the issue itself at https://github.com/ecphp/cas-bundle/issues/97

2024-02-20 09:47 UTC, StudioAH commented
Hello, No testing was done for both SF 6 & 7. Therefore I wanted to make sure this would work. But if you want to work on it be my guest because I am struggling to test it locally atm.

2024-02-20 09:52 UTC, StudioAH commented
Yes but your  comment was right, my code was not considering the bundle to work for both symfony 6 and 7 at the same time. It needed some changes `^6.0 | ^7.0` for exemple

2024-02-20 09:54 UTC, drupol commented
OK OK !

Yeah if you could reopen your PR and update to `^6.0 || ^7.0` (mind the 2 `|`), it could be nice, so you could tell me if it works, and if it is successful, I can cut a release and also close the aforementionned issue!

2024-02-20 10:04 UTC, drupol requested changes

2024-02-20 10:04 UTC, drupol commented on composer.json
> +        "symfony/cache": "^7.0",
Could you keep `^6.0 || ^7.0` for `symfony/cache` too ?

2024-02-20 10:06 UTC, drupol requested changes
Could you also use `^6.1` in place of `^6.0` ?

2024-02-20 10:11 UTC, drupol commented
Nice! Thank you very much. 

@Punt13140 Do you mind testing that branch and see if it works on your side? In case of a yes, I'll cut a new release immediately.

2024-02-20 16:26 UTC, Punt13140 commented
I quickly tried to install the bundle in a new Symfony 7 project, and it doesn't work out of the box.

I have dependency problems with 

`"psr/http-message": "^1.0",`

Trying to change 

`"psr/http-message": "^1.0|^2.0",`

We have another dependency problem with 

`loophp/psr-http-message-bridge-bundle`

which depends on 
`"symfony/psr-http-message-bridge": "^1 || ^2"`

However, it seems that the latter now follows Symfony tags since 6.4...

> Import the bridge into the Symfony monorepo and synchronize releases
https://github.com/symfony/psr-http-message-bridge/blob/v6.4.3/CHANGELOG.md

2024-10-09 09:32 UTC, merged

2024-10-09 09:33 UTC, drupol commented
Merging this PR and continue the work in #100 !

2024-10-09 09:33 UTC, drupol commented
Thank you both !!!